ТЕОРИЯ

1 Соревнование

Получается нам дана первичная структура белка - линейная последовательность a1..an аминокислотных остатков в молекуле белка. Нужно получить третичную - расположение элементов вторичной структуры (альфа-спиралей и бета- слоев) в пространстве относительно один другого. 
Таким образом из первичной струткуры сначала нужно получить вторичную, а из нее уже третичную. 

Существующие техники изучения третичной структуры белка — пространственной укладки изгибов, листов и спиралей аминокислотной цепи — проблематичны. Методы разрешения топологии белка включают электронную микроскопию, рентгеноструктурный анализ и ядерную магнитно-резонансную спектроскопию. Чтобы применять их, необходим кристаллизованный белок, замороженный белок, химически обработанный белок или радиоактивно меченный белок соответственно. К тому же сложность процесса подготовки образца усугубляется высокой стоимостью методов.

Я, как начальник лаборатории, нашел решение в применении искусственного интеллекта, так как вышуепомятнутые методы затруднительны. В 2018 году Google DeepMind представила алгоритм AlphaFold, который обошел предшественников по эффективности. На основе последовательности аминокислот нейросеть:

1) Предсказывает расстояния между всеми парами аминокислотных остатков 

2) Предсказывает углы между связями, соединяющими аминокислоты.

К тому же алгоритм самостоятельно оценивает точность своих расчетов.


In [1]:
from numpy import *

def algorithm(ch1, ch2):
    n=len(ch1)+1
    k=len(ch2)+1
    m=[[0 for j in range (k)] for i in range(n)]
    for i in range(n):
        m[i][0]=i
    for j in range(k):
        m[0][j]=j
    for i in range(1,n):
        for j in range(1,k):
            m[i][j]=min(m[i-1][j-1]+ (1 if ch1[i-1]!=ch2[j-1] else 0),m[i][j-1]+1,m[i-1][j]+1)
    print(reshape(m,(n,k)))
    print("Wage is ", m[n-1][k-1])
    
    i=n-1
    j=k-1
    
    resch1=""
    resch2=""
    while i!=0 or j!=0:
        if m[i-1][j-1]<=m[i-1][j] and m[i-1][j-1]<=m[i][j-1]:
            resch1=ch1[i-1]+resch1
            resch2=ch2[j-1]+resch2
            i-=1
            j-=1
        elif m[i-1][j]<=m[i-1][j-1] and m[i-1][j]<=m[i][j-1]:
            resch1=ch1[i-1]+resch1
            resch2="-"+resch2
            i-=1
        else:
            resch1="-"+resch1
            resch2=ch2[j-1]+resch2
            j-=1
    print(resch1)
    print(resch2)

In [2]:
chain1="CCAAGGCT"
chain2="CCAGAGAC"
algorithm(chain1,chain2)

[[0 1 2 3 4 5 6 7 8]
 [1 0 1 2 3 4 5 6 7]
 [2 1 0 1 2 3 4 5 6]
 [3 2 1 0 1 2 3 4 5]
 [4 3 2 1 1 1 2 3 4]
 [5 4 3 2 1 2 1 2 3]
 [6 5 4 3 2 2 2 2 3]
 [7 6 5 4 3 3 3 3 2]
 [8 7 6 5 4 4 4 4 3]]
Wage is  3
CCA-AGGCT
CCAGAGAC-


In [3]:
chain1="CCAAGGCT"
chain2="CCAAGGCT"
algorithm(chain1,chain2)

[[0 1 2 3 4 5 6 7 8]
 [1 0 1 2 3 4 5 6 7]
 [2 1 0 1 2 3 4 5 6]
 [3 2 1 0 1 2 3 4 5]
 [4 3 2 1 0 1 2 3 4]
 [5 4 3 2 1 0 1 2 3]
 [6 5 4 3 2 1 0 1 2]
 [7 6 5 4 3 2 1 0 1]
 [8 7 6 5 4 3 2 1 0]]
Wage is  0
CCAAGGCT
CCAAGGCT


Последовательности гомологичны

In [4]:
chain1="AAAGCA"
chain2="AAAGCC"
algorithm(chain1,chain2)

[[0 1 2 3 4 5 6]
 [1 0 1 2 3 4 5]
 [2 1 0 1 2 3 4]
 [3 2 1 0 1 2 3]
 [4 3 2 1 0 1 2]
 [5 4 3 2 1 0 1]
 [6 5 4 3 2 1 1]]
Wage is  1
AAAGCA
AAAGCC


Последовательности не схожи разной длины

In [5]:
chain1="AAA"
chain2="GACTAGGA"
algorithm(chain1,chain2)

[[0 1 2 3 4 5 6 7 8]
 [1 1 1 2 3 4 5 6 7]
 [2 2 1 2 3 3 4 5 6]
 [3 3 2 2 3 3 4 5 5]]
Wage is  5
-A--A--A
GACTAGGA


In [6]:
chain1="GAAATGAA"
chain2="GACTAGGA"
algorithm(chain1,chain2)

[[0 1 2 3 4 5 6 7 8]
 [1 0 1 2 3 4 5 6 7]
 [2 1 0 1 2 3 4 5 6]
 [3 2 1 1 2 2 3 4 5]
 [4 3 2 2 2 2 3 4 4]
 [5 4 3 3 2 3 3 4 5]
 [6 5 4 4 3 3 3 3 4]
 [7 6 5 5 4 3 4 4 3]
 [8 7 6 6 5 4 4 5 4]]
Wage is  4
GA-AATGAA
GACTAGGA-
